/**
 * Globo Rojo open source application
 *
 *  Copyright © 2013, 2014 by Mauro Magnasco <mauro.magnasco@gmail.com>
 *
 *  Licensed under GNU General Public License 2.0 or later.
 *  Some rights reserved. See COPYING, AUTHORS.
 *
 * @license GPL-2.0+ <http://spdx.org/licenses/GPL-2.0+>
 */

//==================== Font Name ======================//

#define CUSTOM_FONT                     @"SegoeWP"


//==================== Server Info ====================//

//#define SERVER_HOST                     @"http://192.168.0.178"
#define SERVER_HOST                     @"http://meri.to"


#define hv1                             @"X-MICROTIME"
#define hv2                             @"X-HASH"
#define APP_SECRET_KEY                  @"3KFC94J859FJH29KV9KHZ9C49393JFZ5"


#define SITE_NAME                       @"BalloonRed"

#define LOGIN_URL                       @"/ws/loginSubmit.php"
#define LOGIN_SOCIAL_URL                @"/ws/loginSocial.php"
#define FORGOT_URL                      @"/ws/forgotPassword.php"
#define REQUEST_VIDEO_ITEM_URL          @"/ws/getMyVideoList.php"
#define REGISTER_VIDEO_URL              @"/ws/addVideo.php"
#define DELETE_VIDEO_URL                @"/ws/deleteVideo.php"
#define DELETE_COMMENT_URL              @"/ws/deleteComment.php"
#define REPORT_VIDEO_URL                @"/ws/reportVideo.php"
#define REPORT_COMMENT_URL              @"/ws/reportComment.php"
#define GET_VIDEOINFO_URL               @"/ws/getVideoInfoForScore1.php"
#define SAVE_COMMENT_URL                @"/ws/saveComment.php"
#define SAVE_VIDEOSCORE_URL             @"/ws/saveVideoScore.php"
#define GET_CURRENTTIME_URL             @"/ws/getCurrentTime.php"
#define CHECK_NOTIFICATION_URL          @"/ws/isNewNotificationExist.php"
#define GET_NOTIFICATION_URL            @"/ws/getNotificationList.php"
#define GET_SEARCH_VIDEO_LIST_URL       @"/ws/getSearchVideoList.php"
#define GET_SEARCH_USER_LIST_URL        @"/ws/getSearchUserList.php"
#define GET_MY_USER_LIST_URL            @"/ws/getMyUserList.php"
#define GET_USER_PROFILE_INFO_URL       @"/ws/getUserProfileInfo.php"
#define SET_NOTI_STATUS_READED_URL      @"/ws/setNotificationReadStatus.php"
#define GET_USERID_FROMUSERNAME_URL     @"/ws/getUserIdFromUsername.php"
#define SIGNUP_FACEBOOK_URL             @"/ws/signUpFacebook.php"
#define SIGNUP_TWITTER_URL              @"/ws/signUpTwitter.php"
#define SIGNUP_REGISTRATION_URL         @"/ws/signUpRegistration.php"
#define SIGNUP_SUBMIT_URL               @"/ws/signUpSubmit.php"
#define SET_FOLLOW_URL                  @"/ws/setFollow.php"
#define GET_SOCIALINFO_URL              @"/ws/socialConnectedInfo.php"
#define GET_VIDEOLIST_BYUSER_URL        @"/ws/getVideoListByUserId.php"
#define UPLOAD_PICTURE_URL              @"/ws/uploadPicture.php"
#define CROP_PICTURE_URL                @"/ws/cropPicture.php"
#define DELETE_PROFILEPICTURE_URL       @"/ws/deleteProfilePicture.php"
#define DELETE_PROFILEACCOUNT_URL       @"/ws/deleteProfileAccount.php"
#define FACEBOOK_CONNECT_URL            @"/ws/facebookConnect.php"
#define TWITTER_CONNECT_URL             @"/ws/twitterConnect.php"
#define FACEBOOK_FRIENDS_URL            @"/ws/facebookFriends.php"
#define TWITTER_FRIENDS_URL             @"/ws/twitterFriends.php"
#define SAVE_PROFILESETTINGS_URL        @"/ws/saveProfileSetting.php"
#define FOLLOW_LIST_URL                 @"/ws/followerList.php"
#define FOLLOWING_LIST_URL              @"/ws/followingList.php"
#define DISCONNECT_URL                  @"/ws/socialDisconnect.php"
#define NOTI_GET_VIDEOINFO_URL          @"/ws/getVideoInfo.php"
#define SET_FOLLOW_URL                  @"/ws/setFollow.php"
#define SHARE_EMAIL_URL                 @"/ws/shareVideoEmail.php"
#define REFRESH_HOMEVIDEO_URL           @"/ws/refreshMyVideoList.php"
#define REFRESH_MYUSERLIST_URL          @"/ws/refreshMyUserList.php"
#define REFRESH_SEARCHUSERLIST_URL      @"/ws/refreshSearchUserList.php"
#define REFRESH_SEARCHVIDEO_URL         @"/ws/refreshSearchVideoList.php"
#define SET_DEV_TOKEN_URL               @"/ws/setDevIdToUser.php"
#define DELETE_DEV_TOKEN_URL            @"/ws/deleteDevIdFromUser.php"
#define SET_BADGE_COUNT_URL             @"/ws/setBadgeCount.php"
#define RESET_HASHTAG_URL               @"/ws/resetHashtag.php"
#define GET_HASHTAGLIST_URL             @"/ws/getDefaultHashtag.php"
#define GET_NOTISTATUS_URL              @"/ws/getEmailNotificationStatus.php"
#define SAVE_NOTISTATUS_URL             @"/ws/saveEmailNotificationStatus.php"
#define GET_HASHTAG_URL                 @"/ws/getDefaultHashtag1.php"
#define GET_PARENTHASHTAG_URL           @"/ws/getParentHashtag.php"




//=================== Request Parameter ==================//

#define TAG_REQ_EMAIL                       @"email"
#define TAG_REQ_PASSWORD                    @"password"
#define TAG_REQ_CNTLOADED                   @"cntLoaded"
#define TAG_REQ_SORT                        @"sort"
#define TAG_REQ_TYPE                        @"type"
#define TAG_REQ_CURRENTTIME                 @"currentTime"
#define TAG_REQ_CNTLAZYLOAD                 @"cntLazyLoad"
#define TAG_REQ_USERID                      @"userId"
#define TAG_REQ_VIDEOURL                    @"videoUrl"
#define TAG_REQ_DESCRIPTION                 @"description"
#define TAG_REQ_CATEGORY                    @"category"
#define TAG_REQ_VIDEOID                     @"videoId"
#define TAG_REQ_COMMENTID                   @"commentId"
#define TAG_REQ_TXTCOMMENT                  @"txtComment"
#define TAG_REQ_SCORE                       @"score"
#define TAG_REQ_TXTKEYWORD                  @"txtKeyword"
#define TAG_REQ_USERNAME                    @"username"
#define TAG_REQ_SNSID                       @"snsId"
#define TAG_REQ_USERNAME                    @"username"
#define TAG_REQ_NAME                        @"name"
#define TAG_REQ_EMAIL                       @"email"
#define TAG_REQ_TOKEN                       @"token"
#define TAG_REQ_PHOTO                       @"photo"
#define TAG_REQ_TOKEN1                      @"token1"
#define TAG_REQ_TOKEN2                      @"token2"
#define TAG_REQ_USERSNSID                   @"userSnsId"
#define TAG_REQ_FOLLOWINGID                 @"followingId"
#define TAG_REQ_SNSTYPE                     @"snsType"
#define TAG_REQ_SHAREFACEBOOK               @"shareFacebook"
#define TAG_REQ_SHARETWITTER                @"shareTwitter"
#define TAG_REQ_CURRENTUSERID               @"currentUserId"
#define TAG_REQ_IMAGEDATA                   @"imageData"
#define TAG_REQ_IMAGETYPE                   @"imageType"
#define TAG_REQ_X                           @"x"
#define TAG_REQ_Y                           @"y"
#define TAG_REQ_W                           @"w"
#define TAG_REQ_H                           @"h"
#define TAG_REQ_SWITDH                      @"sWidth"
#define TAG_REQ_SHEIGHT                     @"sHeight"
#define TAG_REQ_SRCIMG                      @"srcImg"
#define TAG_REQ_FOLLOWINGID                 @"followingId"
#define TAG_REQ_PERIOD                      @"period"
#define TAG_REQ_DEVTOKEN                    @"devToken"
#define TAG_REQ_COUNT                       @"count"
#define TAG_REQ_HASHTAG                     @"hashtag"
#define TAG_REQ_MENTIONYN                   @"mentionYn"
#define TAG_REQ_SCOREYN                     @"scoreYn"
#define TAG_REQ_COMMENTYN                   @"commentYn"
#define TAG_REQ_FOLLOWYN                    @"followYn"
#define TAG_REQ_UNFOLLOWYN                  @"unfollowYn"
#define TAG_REQ_KEYWORD                     @"keyword"



//=================== Response Parameter ===================//

#define TAG_RES_RESULT                      @"result"
#define TAG_RES_ERROR                       @"error"
#define TAG_RES_USERID                      @"userId"
#define TAG_RES_RB_VIDEO                    @"rb_video"
#define TAG_RES_RB_USER                     @"rb_user"
#define TAG_RES_RB_VIDEO_URL                @"rb_video_url"
#define TAG_RES_RB_CONTENT                  @"rb_content"
#define TAG_RES_RB_HASHTAG                  @"rb_hashtag"
#define TAG_RES_RB_VIDEO_THUMB_LARGE        @"rb_video_thumb_large"
#define TAG_RES_RB_VIDEO_THUMB_SMALL        @"rb_video_thumb_small"
#define TAG_RES_RB_VIDEO_SCORE              @"rb_video_score"
#define TAG_RES_RB_VIDEO_TYPE               @"rb_video_type"
#define TAG_RES_RB_VALID_YN                 @"rb_valid_yn"
#define TAG_RES_RB_CREATED_TIME             @"rb_created_time"
#define TAG_RES_RB_UPDATED_TIME             @"rb_updated_time"
#define TAG_RES_RB_USERNAME                 @"rb_username"
#define TAG_RES_RB_PHOTO                    @"rb_photo"
#define TAG_RES_RB_SCORE                    @"rb_score"
#define TAG_RES_RB_GIVEN_SCORE              @"rb_given_score"
#define TAG_RES_RB_EMAIL                    @"rb_email"
#define TAG_RES_RB_CRED                     @"rb_cred"
#define TAG_RES_TIMEAGO                     @"timeAgo"
#define TAG_RES_VIDEOID                     @"videoId"
#define TAG_RES_IMAGE                       @"image"
#define TAG_RES_TITLE                       @"title"
#define TAG_RES_COMMENTID                   @"commentId"
#define TAG_RES_USERNAME                    @"username"
#define TAG_RES_CNTVIEW                     @"cntView"
#define TAG_RES_CNTSHARE                    @"cntShare"
#define TAG_RES_CNTCOMMENT                  @"cntComment"
#define TAG_RES_CNTSCORE                    @"cntScore"
#define TAG_RES_ISSCORED                    @"isScored"
#define TAG_RES_GIVENSCORE                  @"givenScore"
#define TAG_RES_DATAVIDEO                   @"dataVideo"
#define TAG_RES_SCORELIST                   @"scoreList"
#define TAG_RES_CURRENTTIME                 @"currentTime"
#define TAG_RES_VIDEOLIST                   @"videoList"
#define TAG_RES_COMMENTLIST                 @"commentList"
#define TAG_RES_VIDEOURL                    @"videoURL"
#define TAG_RES_RB_USER_VIDEO_COMMENT       @"rb_user_video_comment"
#define TAG_RES_ISNEWNOTIFICATION           @"isNewNotification"
#define TAG_RES_RB_SENDER_PHOTO             @"rb_sender_photo"
#define TAG_RES_RB_SENDER                   @"rb_sender"
#define TAG_RES_RB_SENDER_USERNAME          @"rb_sender_username"
#define TAG_RES_NOTIFICATIONLIST            @"notificationList"
#define TAG_RES_RB_TYPE                     @"rb_type"
#define TAG_RES_USERLIST                    @"userList"
#define TAG_RES_RB_NAME                     @"rb_name"
#define TAG_RES_PHOTO                       @"photo"
#define TAG_RES_CNTVIDEOS                   @"cntVideos"
#define TAG_RES_CNTFOLLOWERS                @"cntFollowers"
#define TAG_RES_CNTFOLLOWING                @"cntFollowing"
#define TAG_RES_USERSNSID                   @"userSnsId"
#define TAG_RES_CONNECTFACEBOOK             @"connectFacebook"
#define TAG_RES_CONNECTTWITTER              @"connectTwitter"
#define TAG_RES_CATEGORYLIST                @"categoryList"
#define TAG_RES_RBHASHTAG                   @"rb_hashtag"
#define TAG_RES_SCORE                       @"score"
#define TAG_RES_USERLIST                    @"userList"
#define TAG_RES_ISFOLLOWING                 @"isFollowing"
#define TAG_RES_VIDEOITEM                   @"videoItem"
#define TAG_RES_VIDEOSCORE                  @"videoScore"
#define TAG_RES_ISFOLLOWING                 @"isFollowing"
#define TAG_RES_ISFOLLOWER                  @"isFollower"
#define TAG_RES_HASHTAGLIST                 @"hashtagList"
#define TAG_RES_RB_PARENT_HASHTAG           @"rb_parent_hashtag"
#define TAG_RES_RB_HASHTAG_SCORE            @"rb_hashtag_score"
#define TAG_RES_MYHASHTAGSCORE              @"myHashtagScore"
#define TAG_RES_MYGIVENSCORE                @"myGivenScore"
#define TAG_RES_MYUSERNAME                  @"myUsername"
#define TAG_RES_MENTIONYN                   @"mentionYn"
#define TAG_RES_SCOREYN                     @"scoreYn"
#define TAG_RES_COMMENTYN                   @"commentYn"
#define TAG_RES_FOLLOWYN                    @"followYn"
#define TAG_RES_UNFOLLOWYN                  @"unfollowYn"
#define TAG_RES_PARENTHASHTAG               @"parentHashtag"



//==================== Values of Parameter ======================//

#define TAG_SUCCCESS                        @"success"
#define TAG_FAILED                          @"failed"
#define TAG_ALREADY                         @"ALREADY"
#define TAG_OWNER                           @"OWNER"

//==================== Notification Names =======================//

#define IFTweetLabelURLNotification         @"IFTweetLabelURLNotification"
#define IFTweetLabelUserNotification        @"IFTweetLabelUserNotification"
#define IFTWeetLabelPostNotification        @"IFTweetLabelPostNotification"
#define IFNotiLabelUserNotification         @"IFNotiLabelUserNotification"
#define IFNotiLabelPostNotification         @"IFNotiLabelPostNotification"
#define IFNotiLabelFindUserNotification     @"IFNotiLabelFindUserNotification"
#define IFNotiLabelFollowUserNotification   @"IFNotiLabelFollowUserNotification"
#define IFNotiLabelFollowingUserNotification    @"IFNotiLabelFollowingUserNotification"

//==================== User Defaults Parameter =================//

#define IFTweetLabelButtonTitle             @"IFTweetLabelButtonTitle"
#define IFNotiLabelButtonTitle              @"IFNotiLabelButtonTitle"


